name: Check CI runs
description: Check for a successful CI workflow run with the same tree

inputs:
  ci_workflows:
    description: "CI workflow names (comma-delimited)"
    required: true
outputs:
  ci_required:
    description: "Whether a CI workflow run is required for the current tree (0 = no, 1 = yes)"
    value: ${{ steps.get-ci-required.outputs.ci_required }}

runs:
  using: composite
  steps:
    - name: Checkout
      if: ${{ hashFiles('.git/config') == '' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check for a successful run with the same tree
      id: get-ci-required
      shell: bash
      run: |
        "$github_action_path/check-ci-runs.sh" >>"$GITHUB_OUTPUT"
      env:
        github_action_path: ${{ github.action_path }}
        ci_run_id: ${{ github.run_id }}
        ci_workflows: ${{ inputs.ci_workflows }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: check-ci-runs-metadata
        path: ${{ steps.get-ci-required.outputs.artifact_dir }}

branding:
  color: purple
  icon: cloud-off
